services:
  app:
    image: ghcr.io/realmotz/manjarmio:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      NITRO_HOST: 0.0.0.0
      NITRO_PORT: 3000
      NODE_ENV: production
      NUXT_PUBLIC_PICKUP_ADDRESS: ${PICKUP_ADDRESS:-}
      NUXT_PUBLIC_PICKUP_ADDRESS2: ${PICKUP_ADDRESS2:-}
      NUXT_PUBLIC_WHATSAPP_BUSINESS_NUMBER: ${WHATSAPP_BUSINESS_NUMBER}
      NUXT_PUBLIC_WORKING_HOURS_START: ${WORKING_HOURS_START}
      NUXT_PUBLIC_WORKING_HOURS_END: ${WORKING_HOURS_END}
      NUXT_PUBLIC_DELIVERY_HOURS_START: ${DELIVERY_HOURS_START}
      NUXT_PUBLIC_DELIVERY_HOURS_END: ${DELIVERY_HOURS_END}
      NUXT_PUBLIC_SUPABASE_URL: ${SUPABASE_URL}
      NUXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: ${SUPABASE_PUBLISHABLE_KEY}
      NUXT_SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY}
      NUXT_ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      NUXT_SESSION_PASSWORD: ${NUXT_SESSION_PASSWORD}
    restart: always
